### PR TITLE
feature/GAPDC-34 - creates front-end login page

### PR DESCRIPTION
**Pull request by sainab-omar**
This PR:

- Creates a static render of the Home component
- Sets up redux store and creates 'home' slice for page navigation using CSS
- Creates Login component
- Uses redux states and styling to show different pages 'onClick' of buttons

Below is an image of the Login page:

image

### CODE REVIEW

**Comment by ellisrichardj** [comment]
Looks great - good work

**Review by ellisrichardj — APPROVED** [review]

**Review by Hira-Naveed — APPROVED** [review]
Looking great Sainab, fab job 🥇

**Review by televisedbrain — APPROVED** [review]
Great work!

**Comment by praveenmurugan101** [comment]
Looking good!

**Pull request merged**
